version: "3.8"

services:
  backend:
    container_name: api
    build: 
      context: ./api
    ports:
      - "5000:5000"
    expose:
      - 5000

  frontend:
    container_name: client
    build:
      context: ./client
    stdin_open: true
    volumes:
      - ./client:/client
    expose:
      - 5173
    ports:
      - "5173:5173"
    depends_on:
      - backend

  reverse_proxy:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - backend
      - frontend