"""empty message

Revision ID: 2412a039a5e5
Revises: 5aca6da5442f
Create Date: 2023-08-04 18:32:46.273207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2412a039a5e5'
down_revision = '5aca6da5442f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('pos',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('pos',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
