"""empty message

Revision ID: 30a1c25edc04
Revises: 0def0cc7e42a
Create Date: 2023-08-04 18:31:53.421333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a1c25edc04'
down_revision = '0def0cc7e42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_review', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('last_review')

    # ### end Alembic commands ###
