"""empty message

Revision ID: 31416ff324b4
Revises: 3452429d2158
Create Date: 2023-08-05 07:34:35.095286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31416ff324b4'
down_revision = '3452429d2158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_column('seen')

    # ### end Alembic commands ###
