"""empty message

Revision ID: 3452429d2158
Revises: 2412a039a5e5
Create Date: 2023-08-05 07:28:45.322526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3452429d2158'
down_revision = '2412a039a5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('due', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('easing_factor', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('easing_factor')
        batch_op.drop_column('interval')
        batch_op.drop_column('due')
        batch_op.drop_column('seen')

    # ### end Alembic commands ###
